id: DBB70FE49
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-08T06:46:54+00:00'
last_modified: '2022-05-26T12:14:16.970398+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    b39f:
      image_group_id: I1PD95882
      title: འཕགས་པ་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ཁརྶ་པཱ་ཎིའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      order: 37
      base_file: b39f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
