id: PB4BBB4BB
initial_creation_type: ocr
source_metadata:
  volumes:
    5ea1453fbaa54f2981ba3154e1b4e0d6:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: འཕགས་པ་སྤྱན་རས་གཟིགས་དབང་ཕྱུག་ཁརྶ་པཱ་ཎིའི་སྒྲུབ་ཐབས།
      total_pages: 1379
      volume_number: 37
